// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgbRYGaMj3eOLeyCU6GufQHmOnN9pTLEw',
    appId: '1:77420022549:web:0fcf2d14f8081ba02c771c',
    messagingSenderId: '77420022549',
    projectId: 'smarttrade-83ad0',
    authDomain: 'smarttrade-83ad0.firebaseapp.com',
    storageBucket: 'smarttrade-83ad0.firebasestorage.app',
    measurementId: 'G-YCMJ6R0KXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSbfoVlS7eJi_n4rXukH1a7okx5mWiC0',
    appId: '1:77420022549:android:4632961226ec8b382c771c',
    messagingSenderId: '77420022549',
    projectId: 'smarttrade-83ad0',
    storageBucket: 'smarttrade-83ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdOtFAuQe2cPSNuYUF2FfWHar0M-3234g',
    appId: '1:77420022549:ios:cbac6abf764d67432c771c',
    messagingSenderId: '77420022549',
    projectId: 'smarttrade-83ad0',
    storageBucket: 'smarttrade-83ad0.firebasestorage.app',
    iosBundleId: 'com.example.smarttrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdOtFAuQe2cPSNuYUF2FfWHar0M-3234g',
    appId: '1:77420022549:ios:cbac6abf764d67432c771c',
    messagingSenderId: '77420022549',
    projectId: 'smarttrade-83ad0',
    storageBucket: 'smarttrade-83ad0.firebasestorage.app',
    iosBundleId: 'com.example.smarttrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgbRYGaMj3eOLeyCU6GufQHmOnN9pTLEw',
    appId: '1:77420022549:web:00cc8628b42c8c462c771c',
    messagingSenderId: '77420022549',
    projectId: 'smarttrade-83ad0',
    authDomain: 'smarttrade-83ad0.firebaseapp.com',
    storageBucket: 'smarttrade-83ad0.firebasestorage.app',
    measurementId: 'G-SZ7774Z9GD',
  );
}
