// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJNDvxUlMEnTGz2uN-x4DAQkDKiPMA_4',
    appId: '1:224373534360:web:2cb23b7440601a7df02aed',
    messagingSenderId: '224373534360',
    projectId: 'hw04-765b9',
    authDomain: 'hw04-765b9.firebaseapp.com',
    storageBucket: 'hw04-765b9.firebasestorage.app',
    measurementId: 'G-MVJGF4VCSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8LgGQmiHi7oYvhtZcmMqifIOQmzy-klk',
    appId: '1:224373534360:android:ae3b5c742f324555f02aed',
    messagingSenderId: '224373534360',
    projectId: 'hw04-765b9',
    storageBucket: 'hw04-765b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHvM8fZHDDA3r9oAlAkNdkbW5NBiaM1po',
    appId: '1:224373534360:ios:1fad2662cb71dc09f02aed',
    messagingSenderId: '224373534360',
    projectId: 'hw04-765b9',
    storageBucket: 'hw04-765b9.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHvM8fZHDDA3r9oAlAkNdkbW5NBiaM1po',
    appId: '1:224373534360:ios:1fad2662cb71dc09f02aed',
    messagingSenderId: '224373534360',
    projectId: 'hw04-765b9',
    storageBucket: 'hw04-765b9.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtJNDvxUlMEnTGz2uN-x4DAQkDKiPMA_4',
    appId: '1:224373534360:web:3dd642ce841c9003f02aed',
    messagingSenderId: '224373534360',
    projectId: 'hw04-765b9',
    authDomain: 'hw04-765b9.firebaseapp.com',
    storageBucket: 'hw04-765b9.firebasestorage.app',
    measurementId: 'G-91C88Z7G58',
  );
}
