// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPbFYTF23nY9BBz7l-RlDhSJClcaiBuIU',
    appId: '1:300099990321:web:cdb1b3312c7ce11dee7610',
    messagingSenderId: '300099990321',
    projectId: 'clw06-3c951',
    authDomain: 'clw06-3c951.firebaseapp.com',
    storageBucket: 'clw06-3c951.firebasestorage.app',
    measurementId: 'G-LQP1P6S7TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4nQEj-hZ3bmkZoqhgzkey_i95k3_4eKQ',
    appId: '1:300099990321:android:7f5b15861c8930d5ee7610',
    messagingSenderId: '300099990321',
    projectId: 'clw06-3c951',
    storageBucket: 'clw06-3c951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjar3aO0Lip5zsDmS3Qxb5NUsYskLiwgY',
    appId: '1:300099990321:ios:45b653759f5c28a4ee7610',
    messagingSenderId: '300099990321',
    projectId: 'clw06-3c951',
    storageBucket: 'clw06-3c951.firebasestorage.app',
    iosBundleId: 'com.example.clw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjar3aO0Lip5zsDmS3Qxb5NUsYskLiwgY',
    appId: '1:300099990321:ios:45b653759f5c28a4ee7610',
    messagingSenderId: '300099990321',
    projectId: 'clw06-3c951',
    storageBucket: 'clw06-3c951.firebasestorage.app',
    iosBundleId: 'com.example.clw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPbFYTF23nY9BBz7l-RlDhSJClcaiBuIU',
    appId: '1:300099990321:web:c4625a9d8780d6b5ee7610',
    messagingSenderId: '300099990321',
    projectId: 'clw06-3c951',
    authDomain: 'clw06-3c951.firebaseapp.com',
    storageBucket: 'clw06-3c951.firebasestorage.app',
    measurementId: 'G-FRLQK8BJSC',
  );
}
